builds:
  - goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/autorelease-test
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
