#!/bin/sh
#/ script/cibuild is run by CI to test this project. It can also be run locally.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/test

# In CI, only run the rest on Linux. Assuming RUNNER_OS is only set by GitHub Actions.
if [ -n "$RUNNER_OS" ] && [ "$RUNNER_OS" != "Linux" ]; then
  exit 0
fi

script/lint
script/generate --check
