#!/bin/sh
#/ script/pre-release is run by release-train as pre-release-hook

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

[ -n "$RELEASE_TAG" ] || {
  echo "RELEASE_TAG must be set"
  exit 1
}

if git rev-parse "$RELEASE_TAG" >/dev/null 2>&1; then
  echo "tag $RELEASE_TAG already exists"
  exit 0
fi

echo "$RELEASE_TAG" > cmd/autorelease-test/version.txt
git diff --quiet cmd/autorelease-test/version.txt || exit 10

git tag "$RELEASE_TAG"

script/bindown -q install goreleaser
bin/goreleaser release --clean --skip-publish
[ -n "$ASSETS_DIR" ] || exit 0
cp dist/checksums.txt dist/autorelease-test_*.tar.gz "$ASSETS_DIR"
