name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      # needed for release
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-go-
      - run: script/cibuild

      # release on pushes to main
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: release
        uses: WillAbides/semver-release-action@v1.2.0
        with:
          create_release: "true"
          validate_version: |
            set -e
            MODULE_VERSION_SUFFIX="$(go list -m | grep -o '/v[0-9][0-9]*$' || true)"
            MAJOR_VERSION="${RELEASE_VERSION%%.*}"
            if [ "$MAJOR_VERSION" -ge 2 ] && [ "$MODULE_VERSION_SUFFIX" != "/v$MAJOR_VERSION" ]; then
              echo "module version suffix must be /v$MAJOR_VERSION"
              exit 1
            elif [ "$MAJOR_VERSION" -lt 2 ] && [ -n "$MODULE_VERSION_SUFFIX" ]; then
              echo "Module name must not end with /v[0-9][0-9]*"
              exit 1
            fi
          post_release_hook: |
            set -e
            script/bindown install goreleaser
            bin/goreleaser release --clean
