name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ synchronize, opened, reopened, labeled, unlabeled ]
  workflow_dispatch:
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      # needed for release
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git remote -v && env
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-go-
      - uses: tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASER_APP_ID }}
          private_key: ${{ secrets.RELEASER_APP_KEY }}
      - run: script/cibuild
      - name: config
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
      - uses: WillAbides/release-train@v3.1.0
        with:
          create-release: true
          pre-release-hook: script/pre-release
          github-token: ${{ steps.generate-token.outputs.token }}
