name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      # needed for release
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-go-
      - run: script/cibuild

      # release on pushes to main
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: script/release
