name: releasable
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
  workflow_dispatch:
jobs:
  releasable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: script/bindown install -q semver-next
      - name: check releasable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: bin/semver-next "$GITHUB_REPOSITORY" --check-pr "$PR_NUMBER" --require-labels
