name: release
on:
  push:
    branches:
      - main
concurrency: release
jobs:
  release:
    # only run if the repository is WillAbides/autorelease-test
    if: github.repository == 'WillAbides/autorelease-test'
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: script/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
