name: release
on:
  push:
    branches:
      - main
concurrency: release
jobs:
  release:
    # only run if the repository is WillAbides/autorelease-test
    if: github.repository == 'WillAbides/autorelease-test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: script/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
